### ISSUE TITLE
Tuist 세팅

### ISSUE THREAD

**Issue by leemhyungyu** [Nexters/Bottles_iOS#1]
## 작업사항
Tuist 세팅하겠습니다~

## Todo
- [x] Tuist 초기 세팅
- [x] Tuist Templates 세팅
- [x] Tuist Plugin 세팅
- [x] Tuist Dependency 세팅
- [x] Tuist Configuration 세팅
