### ISSUE TITLE
앱 알림 설정 유뮤 등록 API 연결

### ISSUE THREAD

**Issue by JongHoooon** [Nexters/Bottles_iOS#339]
## 작업사항
- 앱 알림 설정 유뮤 등록 API 연결

## Todo
- [ ] 스플래쉬화면에서 체크 후 호출
- [ ] 권한 설정됐을 때 호출
- [ ] 알림 설정 변경 시 변경 사항 반영
